### ISSUE TITLE
Daily and Experimental builds messed up after massive site changes

### ISSUE THREAD

**Issue by Dunravin** [DotBow/Blender-Launcher#65] opened 2021-05-19 05:32 UTC
As of yesterday 18-05-21 I'm seeing double of everything in the daily download tab.

Right now there's two entries for 3.0.0 alpha both dated 19 May 2021, 04:05
One of them never downloads, there's just the copy icon animation far right of the app window next to the listing. It never completes.

When I go to my library to check the one that did download its date is now changed and reads 18 May 2021, 21:41

**Expected behavior**
One listing of each daily build (no duplicates)
Downloaded version time and date match the expected time and date.

**Screenshots**
![1](https://user-images.githubusercontent.com/8136212/118760569-ee5c4280-b86a-11eb-8696-4b99d61d0826.png)
![2](https://user-images.githubusercontent.com/8136212/118760575-f320f680-b86a-11eb-9c6c-5724417e9fd6.png)

Screenshot 1 shows the duplicates for 2.93 beta. There is no duplicate for 3.00 alpha shown as I downloaded 1 of them successfully. Notice the date/time of the 3.0.0 alpha.

Screenshot 2 shows the downloaded 3.0.0 alpha in my library/daily folder. Notice the time/date has changed.

**System (please complete the following information):**
 - Windows 10 Pro 20H2

 - Blender Launcher version: 1.12.0 (freshly downloaded for this report)
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]
 - [Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/6506099/Blender.Launcher.log)

**Additional context**
Worked perfectly until very recently. Is this an issue with the launcher or something to do with how the builds are being published?

Thanks hope this is all helpful.

**Comment by MarkBTomlinson** [comment] 2021-05-19 07:03
Confirmed same issue here same OS version.

**Comment by LarsJandel** [comment] 2021-05-19 08:42
Also, _Daily_ vs. _Experimental_ → they look pretty identical: 🤷‍♂️
![image](https://user-images.githubusercontent.com/32457827/118782812-c5e63f80-b88e-11eb-9f88-6e3186b2697e.png)
![image](https://user-images.githubusercontent.com/32457827/118782862-d0a0d480-b88e-11eb-843f-c45f8df8b6e2.png)
Thanks!

**Comment by DotBow** [comment] 2021-05-19 08:44
Hi! Thanks for report!

Time in in Downloads tab is **when build was uploaded** while in library is **build commit time** (the one you see in splash screen), so it is an intended behavior.

About issue with duplicates - it seems yesterday there was heavy modification of zip archive names as well as on site in general, so need to check what's going on.

**Comment by DotBow** [comment] 2021-05-19 08:53
It seems there is now a lot more straight type splitting of builds going on.. It may take longer than I thought
![изображение](https://user-images.githubusercontent.com/32243930/118784414-ab18c880-b898-11eb-9938-452815e0c4bb.png)

**Comment by DotBow** [comment] 2021-05-19 16:03
I'm sorry to everyone for having issues with BL. 
I will try to take time and fix it in coming days.

**Comment by DotBow** [comment] 2021-05-19 22:13
Fixed in https://github.com/DotBow/Blender-Launcher/releases/tag/1.12.1
The naming of Experimental branches in Library still can be messed up though.

P.S. There is actually a hidden links to sha256 files that caused double entries in Downloads

**Closed by DotBow** 2021-05-19 22:13 UTC
Labels: bug

**Comment by LarsJandel** [comment] 2021-05-19 22:22
Thanks for the fix!

**Comment by DotBow** [comment] 2021-05-20 09:15
Ok, the updater is fixed now, it was late night and I messed up the tags 😑
