### ISSUE TITLE
BlenderOctane not recognized

### ISSUE THREAD

**Issue by dudleystorey** [DotBow/Blender-Launcher#31] opened 2020-11-28 06:11 UTC
Octane provides its own build of Blender to run to rendering engine, provided in a "BlenderOctane" folder, based on 2.8.3. Blender-Launcher stalls trying to load build information for BlenderOctane, and does not add it to the launch list. I have tried renaming the folder to the version, and placing it in "experimental" and "custom" folders, but Blender-Launcher does not recognize it.

System information:
Windows 10

 - Operation system: [e.g. Windows 10]
 - Latest version of Blender-Launcher

**Comment by DotBow** [comment] 2020-11-28 08:11
Hi!
Is there a "Blender Launcher.log" file near by "Blender Launcher.exe"?
Could you also please provide information from console? Run this command from your build folder:
> blender.exe -v
Most likely custom build uses some different template for storing build information.

**Comment by dudleystorey** [comment] 2020-11-28 08:19
No logfile. Results from verbose output on Octane Blender:

Program Files\Blender\experimental\BlenderOctane>blender.exe -v
Blender 2.83.6
        build date: 2020-09-15
        build time: 00:30:34
        build commit date: 2020-09-10
        build commit time: 15:15
        build hash: cc45787a9cfa
        build platform: Windows
        build type:
        build c flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /nologo /J /Gd /MP /bigobj -openmp
        build c++ flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /nologo /J /Gd /MP /EHsc /bigobj /permissive- /Zc:twoPhase- -openmp
        build link flags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152,70656 /INCREMENTAL:NO  /ignore:4049 /ignore:4217 /ignore:4221
        build system: CMake

**Comment by DotBow** [comment] 2020-11-28 10:40
Thanks!
And the last check: 
1. Remove ".blinfo" from "BlenderOctane" folder
2. Place "BlenderOctane" build under "custom" folder
3. Restart Blender Launcher

**Comment by dudleystorey** [comment] 2020-11-28 19:08
No problem! Thanks for responding so quickly. 

- There is no .blinfo file in the BlenderOctone folder
- Placing the folder inside of "custom" replicates the behavior seen earlier (Blender-Launcher hangs on "Loading Build Information", although other builds can still be launched).

**Comment by DotBow** [comment] 2020-11-28 19:29
> 
> 
> No problem! Thanks for responding so quickly.
> 
>     * There is no .blinfo file in the BlenderOctone folder
> 
>     * Placing the folder inside of "custom" replicates the behavior seen earlier (Blender-Launcher hangs on "Loading Build Information", although other builds can still be launched).

I just downloaded this one [Octane 2020.1.5-21.14 for Blender 2.83.6 Stable (free tier)](https://render.otoy.com/forum/viewtopic.php?f=7&t=72241), installed it directly to custom folder and it works absolutely fine for me 🤔 (except that it doesn't properly recognize version and branch)
![изображение](https://user-images.githubusercontent.com/32243930/100524419-17a7ea00-31c9-11eb-977f-62daec16d564.png)

**Comment by dudleystorey** [comment] 2020-11-28 19:46
That's super-weird. I've just tried the same thing, but get the same result as before.

**Comment by DotBow** [comment] 2020-11-28 21:02
Sorry for such troubles 😞 
Please, check if this one works for you:
https://drive.google.com/file/d/1IqkgE7nRv-IfhQJkFuujXxlFkYcDN812/view?usp=sharing

**Comment by DotBow** [comment] 2020-11-29 16:21
Please, check if 1.8.0 https://github.com/DotBow/Blender-Launcher/releases/tag/v1.8.0 fixed issue.

**Comment by dudleystorey** [comment] 2020-11-29 18:16
I'm afraid not. It did pick up the folder (and create ones that I didn't have before, such as "daily"), but it's still stuck on loading build information on BlenderOctane from the custom folder:

![image](https://user-images.githubusercontent.com/2029761/100550045-52933780-3234-11eb-9f66-03bbb03a3a6f.png)

**Comment by DotBow** [comment] 2020-11-29 19:27
> 
> 
> I'm afraid not. It did pick up the folder (and create ones that I didn't have before, such as "daily"), but it's still stuck on loading build information on BlenderOctane from the custom folder:
> 
> ![image](https://user-images.githubusercontent.com/2029761/100550045-52933780-3234-11eb-9f66-03bbb03a3a6f.png)

Ok, lets do it another way...
Please, show me the insides of library folder, custom folder and octane build folder within file explorer.
Will be nice to see header with full path as well.

Also, I read everything again and noticed this:

> Program Files\Blender\experimental\BlenderOctane>blender.exe -v

If you are using Program Files that is C:\Program Files, then you are doomed to unexpected behavior due to UAC protection as said under [Notes > Windows Users](https://github.com/DotBow/Blender-Launcher/wiki/Installation#windows-users).
Change Library Folder to something else if that the case.

**Comment by dudleystorey** [comment] 2020-11-29 21:02
Hi: 

Moved the library folder into Documents. Blender 2.91 is detected and loads fine from Blender-Launcher, but BlenderOctane remains undetected:

![image](https://user-images.githubusercontent.com/2029761/100553424-1b7c5080-324b-11eb-818e-70c6c3f3de02.png)

BlenderOctane is inside "custom" folder. Please let me know if I can provide any more information...

D.

**Comment by DotBow** [comment] 2020-12-01 07:29
Sorry for this troubles! :cold_sweat:
I will send you a build later. It should help to debug part of reading build information.

**Comment by DotBow** [comment] 2020-12-01 08:31
Please, try this one, it should generate "Blender Launcher.log" near by "Blender Launcher.exe" if something is wrong: 
https://drive.google.com/file/d/11XTl6aghjKry0l_4q9-69KBZLOhR0Tpq/view?usp=sharing
Make sure to delete exiting .blinfo from build folder and restart BL.

**Comment by dudleystorey** [comment] 2020-12-08 04:44
Good news, DotBow! The new version (and a reinstall of BlenderOctane) seemed to clear the problem completely. Everything works fine now - thank you so much!

I do have a few small corrections in spelling and grammar for the app: totally understandable, as I suspect that English is not your first language. Please let me know if you'd like me to open a new bug issue to track them; for now, I'll add the errors in the notifications I've seen here:

"New versions of Blender is available!" should be "New versions of Blender _are_ available!"

Similarly, "New builds of Blender is available!" should be "New builds of Blender are available!"

Thank you as always for your excellent work and help.

**Comment by DotBow** [comment] 2020-12-08 12:23
Ouch, such a silly mistake, probably because it was changed couple of times. 
Thanks very much for pointing out!
Does the 1.8.1 fixed issue or the build I provided on gdrive?

**Comment by dudleystorey** [comment] 2020-12-08 15:46
For clarity: I'm using the 1.8.1 build.

**Comment by DotBow** [comment] 2020-12-12 06:35
Let's assume that it was fixed in 1.8.1, otherwise will open separate issue if happen again.
Thanks for feedback!

**Closed by DotBow** 2020-12-12 06:35 UTC
Labels: bug, question
