### ISSUE TITLE
Update msg on win10 appears like 5-6 after another without having new builds available

### ISSUE THREAD

**Issue by 0z3l07** [DotBow/Blender-Launcher#49] opened 2021-01-22 19:46 UTC
**Describe the bug**
Ok this is a weird one....I think 3 days ago it started. Win 10 notifications pop up like 5-6 times in a row, even sometimes on top of each other. But there are only the 2.92/2.93 afaik that gets daily builds. And this can happen multiple times a day when there are not updates normally from blender devs. And the launcher shows weird new builds like from 2020

**To Reproduce**
Have the launcher running I guess^^

**Screenshots**
![Screenshot 2021-01-22 204025](https://user-images.githubusercontent.com/24977832/105537751-aa10c980-5cf2-11eb-8941-f61d2ef4b0bd.png)

**System (please complete the following information):**
 - Operation system: win 10
 - Blender Launcher version: latest 1.9
 - Log file: no log since no crash etc

But its only one msg and not like 5-6 stacked together...maybe win 10 would stack them anyway so it only appears as one.
![Screenshot 2021-01-22 204941](https://user-images.githubusercontent.com/24977832/105538237-65d1f900-5cf3-11eb-983c-dd93af9f961e.png)
I got ~15 dingding sounds in the last h...thats the time it typically starts. Blender only pushes updates ones a day afaik

**Comment by DotBow** [comment] 2021-01-23 16:14
Hi! Thanks for feedback!
Can't reproduce it...
Please, check if 1.9.1 fixes an issue:
https://github.com/DotBow/Blender-Launcher/releases/tag/v1.9.1

**Comment by 0z3l07** [comment] 2021-01-24 00:24
mhm seems like it

**Comment by 0z3l07** [comment] 2021-01-25 20:22
2021-01-24 01:24:15,803 - Windows - Blender Launcher 1.9.1
Traceback (most recent call last):
  File "windows\main_window.py", line 477, in scraper_finished
RuntimeError: Set changed size during iteration

error is prob not related to this down below

got this error and now I cant see any daily or experimental downloads
![Screenshot 2021-01-25 212109](https://user-images.githubusercontent.com/24977832/105761303-4507de80-5f53-11eb-88b2-97a2198dd610.png)

**Comment by DotBow** [comment] 2021-01-25 20:32
Yep, there was another change pushed to the blender site that broke everything again but in other part of scraping code 🤕 
Will try to fix it tomorrow, it is already working in 1.10.0

**Comment by kbrandwijk** [comment] 2021-01-25 23:44
Ah, great thread, I ran into _both_ issues these past days, I'll hold for 1.10. Thanks for the great work!

**Comment by DotBow** [comment] 2021-01-26 11:40
Should be fixed in https://github.com/DotBow/Blender-Launcher/releases/tag/v1.9.2

**Closed** 2021-01-26 22:47 UTC
Labels: question

**Comment by kbrandwijk** [comment] 2021-01-28 19:49
All good now, new versions are back, notifications act normal. Thanks!
